### ISSUE TITLE
mongoose-plugin doesn't update updated_at field on update and findOneAndUpdate

### ISSUE THREAD

**Issue by daniloaf** [niftylettuce/igloo#30]
Hi.

I was having an issue that the `updated_at` field was not being updated when using `update` function. So, I looked at `mongoose-plugin.js` and find that it only defines the `pre('save')` hook, but `update` and `findOneAndUpdate` doesn't trigger it.

Is that a known issue? I wrote a simple plugin that creates the hooks for both cases to fix my problem. Should I create a Pull Request with the code?

Thanks

**Comment by niftylettuce** [comment]
Mongoose itself does not trigger hooks on update nor findOneAndUpdate, see Mongoose docs for more info.

**Comment by daniloaf** [comment]
The most recent versions of mongoose already supports creating hooks for both. See on http://mongoosejs.com/docs/middleware.html. Also, the plugin I wrote works:

```javascript
exports = module.exports = function() {

  return function(Schema) {
    Schema.pre('update', function(next) {
      var update = this.getUpdate();

      update.$set = update.$set || {};
      update.$set.updated_at = new Date();

      update.$setOnInsert = update.$setOnInsert || {};
      update.$setOnInsert.created_at = new Date();

      console.log(update);
      next();
    });

    Schema.pre('findOneAndUpdate', function(next) {
      var update = this.getUpdate();

      // update.$set = update.$set || {};
      update.updated_at = new Date();

      console.log(update);
      next();
    });

    return Schema;
  };

};

exports['@singleton'] = true;
```

So, it really works. The difference from the `save` hook is that `this` is the document, while on the above cases it is a `Query` object.
